### PR TITLE
Fix #1239: FosRestDescriber properly configures Parameter#pattern property

### LINKED ISSUE #1239: FOSRestBundle's `AbstractScalarParam#requirements` should be used for `SWG\Parameter#pattern`
Hello,

I think that by accident [`Parameter#format`](https://github.com/nelmio/NelmioApiDocBundle/blob/v3.1.0/RouteDescriber/FosRestDescriber.php#L57) is set instead of the `pattern` property. I might be wrong but to me, _format_ should be used for different purposes, and FOSRestBundle's `QueryParam#requirements` and `RequestParam#requirements` should be used to configure `Parameter::setPattern()` property.

Right now input validation is completely ignored. With suggestion above it works fine. However, I can't still see in the UI regex pattern for allowed input.

For example, the following FOSRestBundle `QueryParam` annotation would produce input field like shown in the screenshot, but allowed regex is not mentioned, therefore the clients can't really know what is allowed.

```
@QueryParam(name="itemsPerPage", default="20", requirements="\d{1,2}", description="Items per page. Default is `20`.")
```

missing regex pattern

Thanks!

### PR DESCRIPTION
**Pull request by ManInTheBox**
Minor bugfix that configures `Parameter#pattern` property instead of `Parameter#format`.
Tests provided that prove this implementation works as expected.

### CODE REVIEW

File: RouteDescriber/FosRestDescriber.php [hunk 1]
```diff
@@ -54,7 +54,7 @@ public function describe(Swagger $api, Route $route, \ReflectionMethod $reflecti
 
                 $normalizedRequirements = $this->normalizeRequirements($annotation->requirements);
                 if (null !== $normalizedRequirements) {
-                    $parameter->setFormat($normalizedRequirements);
+                    $parameter->setPattern($normalizedRequirements);
```
Comment (GuilhemN) [inline RouteDescriber/FosRestDescriber.php]: We should manage differently requirements when they are a regex or a constraint class imo.
Could you inline the normalizeRequirements() method here and if it's a constraint name, keep using the format field please ?

Comment (ManInTheBox) [reply RouteDescriber/FosRestDescriber.php]: Thanks, will keep you updated.

File: RouteDescriber/FosRestDescriber.php [hunk 2]
```diff
@@ -54,7 +54,18 @@ public function describe(Swagger $api, Route $route, \ReflectionMethod $reflecti
 
                 $normalizedRequirements = $this->normalizeRequirements($annotation->requirements);
                 if (null !== $normalizedRequirements) {
-                    $parameter->setFormat($normalizedRequirements);
+                    if ($normalizedRequirements instanceof Constraint) {
+                        if ($normalizedRequirements instanceof Regex) {
```
Comment (GuilhemN) [inline RouteDescriber/FosRestDescriber.php]: Shouldn't this still be put in ``pattern``?

I think we should only use ``format`` for random constraints.

Comment (ManInTheBox) [reply RouteDescriber/FosRestDescriber.php]: Makes sense. Perhaps I didn't understand the requirements properly.
So we want `Regex` into `pattern` and only other custom classes (the else block) to go into the `format`, right?

Comment (GuilhemN) [reply RouteDescriber/FosRestDescriber.php]: That's right :)

**Comment by ManInTheBox** [comment]
Hey, @GuilhemN I refactored the code a bit and (I believe) fulfilled all the requirements. Could you please review this one more time? Thanks!

File: RouteDescriber/FosRestDescriber.php [hunk 3]
```diff
@@ -52,32 +52,44 @@ public function describe(Swagger $api, Route $route, \ReflectionMethod $reflecti
...
-        if ($requirements instanceof Constraint) {
-            if ($requirements instanceof Regex) {
-                return $requirements->getHtmlPattern();
-            }
 
+        if ($requirements instanceof Regex) {
+            return $requirements->getHtmlPattern();
+        }
+
+        return null;
```
Comment (ManInTheBox) [inline RouteDescriber/FosRestDescriber.php]: I explicitly return `null` and not rely on PHP's default return value which is also `null`. This is more a preference. Feel free to object if you don't like it ;)

File: Tests/Functional/FunctionalTest.php [hunk 4]
```diff
@@ -124,6 +124,22 @@ public function testFOSRestAction()
...
+        $this->assertNull($fooParameter->getFormat());
+
+        $barParameter = $parameters->get('bar', 'formData');
+        $this->assertNotNull($barParameter->getPattern());
+        $this->assertEquals('\d+', $barParameter->getPattern());
+        $this->assertNull($barParameter->getFormat());
+
+        $bazParameter = $parameters->get('baz', 'formData');
+        $this->assertNotNull($bazParameter->getFormat());
+        $this->assertEquals('IsTrue', $bazParameter->getFormat());
```
Comment (ManInTheBox) [inline Tests/Functional/FunctionalTest.php]: I believe this is what we want, right? If they put custom `Constraint` which also **is not** `Regex` constraint, then we want to use only its class short name.

File: RouteDescriber/FosRestDescriber.php [hunk 5]
```diff
@@ -52,32 +52,44 @@ public function describe(Swagger $api, Route $route, \ReflectionMethod $reflecti
                     $parameter->setDescription($annotation->description);
                 }
 
-                $normalizedRequirements = $this->normalizeRequirements($annotation->requirements);
-                if (null !== $normalizedRequirements) {
-                    $parameter->setFormat($normalizedRequirements);
+                $pattern = $this->getPattern($annotation->requirements);
+                if (null !== $pattern) {
```
Comment (ManInTheBox) [inline RouteDescriber/FosRestDescriber.php]: I also don't support assignments in conditional checks, so I didn't want to assign `$pattern` here but instead on the line above, before the conditional check. Feel free to object if this doesn't fit in this project.

**Comment by ManInTheBox** [comment]
You're welcome! ;)
