### PR TITLE
fix: LegacyType deprecation warning in Configuration

### LINKED ISSUE #2677: [Bug]: checking LegacyType triggers deprecation warning
### Version

5.9.2

### Description

usage of the `Symfony\Component\PropertyInfo\Type` as legacy type in this bundle's `Configuration` to define the default value and validation for the 'type_info' config triggers a deprecation warning when using `bin/console debug:container --deprecations` in an application using this bundle

could this check perhaps be inverted by checking for the `Symfony\Component\TypeInfo\Type` instead?

### JSON OpenApi

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lacatoire**
## Summary

- Check for the presence of `Symfony\Component\TypeInfo\Type` instead of the absence of the deprecated `Symfony\Component\PropertyInfo\Type` to avoid triggering a deprecation warning on Symfony 7.x
- Use `!method_exists(PropertyInfoExtractor::class, 'getTypes')` to reliably detect Symfony 8+ for the validation that prevents setting `type_info: false`

Fixes #2677

### CODE REVIEW

File: tests/DependencyInjection/ConfigurationTest.php [hunk 1]
```diff
@@ -263,7 +263,7 @@ public static function provideInvalidConfiguration(): \Generator
             ];
         }
 
-        if (!class_exists(LegacyType::class)) {
+        if (!class_exists('Symfony\Component\PropertyInfo\Type')) {
```
Comment (DjordyKoert) [inline tests/DependencyInjection/ConfigurationTest.php]:
```suggestion
        if (!class_exists(LegacyType::class)) {
```
